console.log('sup')
let list = document.getElementById('list')

let nothinBtn = document.getElementById('nothing')

nothinBtn.addEventListener('click', () => {
  document.write('NEVER GONNA GIVE YOU UP')
  document.write('NEVER GONNA LET YOU DOWN')
  document.write('NEVER GONNA RUN AROUND')
  document.write('NEVER GONNA HURT YOU')
  document.write('peas pudding hot')
  document.write('peas pudding cold')
  document.write('peas pudding in the pot nine days old')
})
console.log('foo')
console.log('bar')
console.log('baz')
console.log('bar')
console.log('foo')
console.log(1 + 2)
console.log(3 + 2)
console.log(4 + 2)
console.log(4 + 2)
console.log(4 + 2)
